### ISSUE TITLE
M4 Investigator - no option to choose "ore type"

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#109]
Where do I choose the “ore type”. This is not clear. When the .mre is opened it is always blank and needs to be reclassified.  Is this because the "save bcf" option is activated?
If so, could there not be a "oretype" option so that when opening it automatically does the reclassification as well?

**Comment by jonathan-knapp** [comment]
Andrew, 
Because of the way that we collect data with M4 no ore type is used in the M4 investigator. The conversion happens when you open in process, so with M4 you will always have to do a reclassification. Perhaps we can consider doing the reclassification in the import window automatically in 3,3. This will be closed.
