### ISSUE TITLE
Update variable associated with each standard spectra 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#13]

**Comment by AHM-amics** [comment]
@knapp-amics, @markguo7

The reason for this is because I am comparing data on the microXRF + with using 50kV and 35kV. This is because we can get 800uA at 35kV without any loss of relevant information. In fact it should improve the light element signal, which will help with various definitions, i.e. make them more robust.

Therefore, I would like to recommend and get feedback about adding the following variables to the mineral/phase standards database.

In my opinion the following variables should be added as they are important to identify if a spectrum is relevant or correct for any given analysis. This list below is given as a variable name and the relevant details of the units or options. Also, some of these options should be variables also associated with the “ore type” so as to avoid the mixing of spectra into incorrect “list”

Energy Source: e-beam (SEM-EDS) or X-ray (XRF-EDS)
Measurement Voltage: (this is a number; units kV)
Max Pulse Throughput: (this is a number; units kcps)
Vacuum: (this is a number; units mbar)
Filter: (Yes / No or True / False); If True then Filter Type: (this is text)
Spectrum Type: (this is a text field with some dropdown options for consistence, e.g. synthetic, mixed, sample, standard)
If synthetic spectrum true, then: Spectrum includes Effects (PileUp etc): (Yes / No or True / False)

These are what occur to me at the moment, but there may be others.
