### ISSUE TITLE
Automate the generation of 2 phase mixes by selecting 3 or more phases 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#15]

**Comment by MarkGuo7** [comment]
We can do that for sure, but not sure it is a good idea.
Need someone to review it.

**Comment by knapp-amics** [comment]
This could be a significant time-saver. I would like to also consider an automated mix-generator that will use adjacent minerals (even if separated by an unknown) that will generate a mix based on what is likely a mix. However, a intermediate step would be to manually select the minerals that we want to combine and automatically generate mixes between all selected.  

We would want to have a one-to-many and a many-to-many options. ****

**Comment by MarkGuo7** [comment]
Then yes. Let's do it.
My only concern is that it is too easy build hundreds without any notice. It will slow the classification and the standard list will be messy.

**Comment by knapp-amics** [comment]
Yea, I understand that. Could we auto-group that? I think we can trust the user to understand that.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AHM-amics** [comment]
@knapp-amics @MarkGuo7 Yes there is a concern that it could generate lots (hundreds) of classifications. Maybe a pop-up warning stating the number of mixes to be generated?
However, This is particularly important for M4 and most users know this and it is stressed during training because mixed information is so common. 
Auto-grouping and Auto-compositions etc would be the next step once this functionality is ready.
