### ISSUE TITLE
X-ray position in segment

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#191]
I think thisissue might already be listed (or closed) but can we look at where the X-ray is positioned in a segment again? To close to the edge/close to another phase leads to unknowns, when the phase should be easily recognized.

These two large segments highlighted by the green rectangles are both classified as unknown because the X-ray was positioned so close to another phase.
  
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/f9e102c6-5882-4dd3-bd21-c7bddfb482c4)

**Comment by Matt-Power** [comment]
Just to add to Gerda's point I've attached a matching mineral / BSE pair - the black is the unknown segment and I've drawn an arrow showing the Xray point for the segment. The point chosen for the Xray is actually mostly off the grain and on quartz (not sphalerite). It's a pretty bizarre place to put a point given the overall size, shape and uniformity of the BSE over the segment.

![AMICSProcess64_6x76PIxvL2](https://user-images.githubusercontent.com/84986921/156234419-8c1cc35e-3c27-4c4f-8e43-2d9d31506004.png)
![AMICSProcess64_CnfAGe4Yky](https://user-images.githubusercontent.com/84986921/156234437-d76de8fc-5c0e-4eb2-b5a8-da2799d04eb5.png)
)

**Comment by Matt-Power** [comment]
Just to add to Gerda's note, here's another example of an odd position for an X-ray point. The black is a single unknown segment and the associated Xray is arrowed - it's been placed right on the edge of the grain even though the segment is pretty uniform and large. The points in the centre of the segment are actually picking out tiny inclusions. For the record, there are no field boundaries near the segment so it's not due to any field overlap challenges.

![AMICSProcess64_zGUZPyQHtD](https://user-images.githubusercontent.com/84986921/156239042-edca2b9b-d9c6-4dc3-b9fc-189a62d1e7bc.png)

![AMICSProcess64_E3IIBUndrK](https://user-images.githubusercontent.com/84986921/156239039-0595cc85-903a-4143-bb1a-7f2cad0807d8.png)

.

**Comment by Matt-Power** [comment]
Has there been any movement on this? I have a batch of measurements that really suffers from this issue - the Xray points are very often placed on top of small inclusions, cracks, and at the edge of segments even though the majority of the segment is uniform and smooth.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt
Which version you are using?
Do you have time to talk about this?
I did something about this issue, but not sure whether it is good enough or not.
If you can send me a sample with issue bookmark positions, that would be great.

**Comment by MarkGuo7** [comment]
@Matt-Power 

Hi Matt

Here is the screen copy of the xray position in your result:
![image](https://user-images.githubusercontent.com/84481724/173749487-2e729cad-d7b1-4156-8fc3-bd59b074c93e.png)

I can see this issue from the version 3.2.1.0
![image](https://user-images.githubusercontent.com/84481724/173749915-26eb6e60-107a-44b2-b27b-9e775729e203.png)

Now the position of the same area would be in 3.3:
![image](https://user-images.githubusercontent.com/84481724/173750151-78611174-8b1c-41fb-86b5-d43e10e4b29b.png)

I think it is better now. Would like to try?

**Comment by MarkGuo7** [comment]
Here is another example:

The bookmark from result:
![image](https://user-images.githubusercontent.com/84481724/173752702-34892b26-ffea-4f05-8e82-94f846aa1f14.png)

The xray position in 3.2(similar with the result)
![image](https://user-images.githubusercontent.com/84481724/173752773-38309deb-ec8a-4a2f-8b25-c35dec64aa7d.png)

Now in 3.3:
![image](https://user-images.githubusercontent.com/84481724/173752899-b99435e2-f179-4873-81ef-9d860f985e41.png)

**Comment by ChiLyMan** [comment]
@Matt-Power Has this been resolved? I've check results I measured recently and the x-ray points seem more centralized (not dead center but not near the edge).

**Comment by Matt-Power** [comment]
Not updated Investigator yet. Will try to find some time to do so next week.

**Comment by MarkGuo7** [comment]
Hi Matt

I fixed the issue of xray positions in 3.2. Here is the new link. Please give it a try.

https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EU2jtv9WQ_JDrHWZmVSJKMABF8uHth2LsrYmbbvwzKbsJA?e=8QvRDg

**Comment by Matt-Power** [comment]
@MarkGuo7 Gave this version a go on some fine-textured samples which caused real problems for the previous version of Investigator - it works way better, thank you.

**Comment by jkabel** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  As an added bonus I'd say it's also about 20% faster without missing anything. Great work.-Jacob                                                                                                                                                                                                                                                                                                                        From: ***@***.***: October 20, 2022 6:03 p.m.To: ***@***.*** to: ***@***.***: ***@***.***: Re: [Bruker-Amics/bugs_features] X-ray position in segment (Issue #191)  
Closed #191 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
