### ISSUE TITLE
Using Energy Channels in Standards

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#222]
The Energy channel criteria is not applied in v3.3.0.660.  It appears that they are ignored completely.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 is this done? It has been "In Progress" for 60 days.

**Comment by AHM-amics** [comment]
Hi Chi and Jonathan.  I believe this bug (comment) was in relation to my testing of this v3.3 version.  I have not used any v3.3 since then and I am back using v3.2 which does not have any energy channel application issues with the exception of the zero value as mentioned in a separate bug (which has a work around, i.e. using negative numbers).  Is there a latest version of v3.3.0.660 which supercedes this. Essentially, for the above bug description, I would enter a energy channel criteria, but it was not applied, i.e. it had no impact on the classification.  Let me know the latest v3.3 version and where I can download it and I will confirm if this bug still applies or not.

**Comment by ChiLyMan** [comment]
Hi Andrew,
I just checked the Energy Range filtering for mineral in version 3.3.0.1315 and have been able to make it exclude/include a mineral using energy range restrictions. Feel free to test it out, but just make sure you select the "Check Energy Range" check box otherwise AMICS will still ignore the energy range setting.
