### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1382 - PROCESS - Errors running a batch calculation on a frame layer

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#226]
Running a batch calculation (e.g. modal mineralogy) on the frame layer of a block measurement results in the following message:

[Measurement Name] does not support the requested granular view mode [2]

The grain and segment layers do appear to work as normal though.

**Comment by jonathan-knapp** [comment]
Test: 3.3.0.1382
This is still not working. ![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/437a2be3-a025-4fe8-a0e8-50f45e09feef)

This is more of a workflow issue. Yes, it is a grain calculation. It would be better still to do the calculation and just default to grain mode. No need to disrupt the workflow (since it is going through the batch process anyway. Could also be confusing if the user did not know what the modes did exactly. Let's try to make this more idiot-proof.

**Comment by ChiLyMan** [comment]
Tested on 1911 on multiple Block data (I had to convert granular to block) and the batch process seems to be working, including exporting a BSE image. Notice that in Block mode "Frame" is now disabled, so only segment and grain layers.
Did someone else want to test on a "native" block measurement.
