### ISSUE TITLE
Classification matching error?

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#271]
There seem to be a problem again in vs 3.3 with the matching detail display and classification result - not sure which is right.

In image below the segment is classified as unknown but the matching detail show a match of 66% when matching probability was set to 58% (no other BSE or priority settings active)
![Classification2.PNG](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/7ccfbd39-f682-471e-908c-061d707f6acf)

The same problem is shown in this example:
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/ea389a75-7bde-416c-b039-ea44f4b3109e)

I can share this file containing these particles with you - I seem unable to upload here.

**Comment by Matt-Power** [comment]
Just to add to Gerda's observations, I've just installed the latest version of 3.3 and unfortunately, the issue seems to be a lot worse than in 3.2:
![image](https://user-images.githubusercontent.com/84986921/186791653-bbb8a916-5013-4397-a361-d90427c53948.png)
This example was a measurement that I fully processed in 3.2 so that unknowns were < 0.01% but after reclassifying in 3.3, the unknowns are now over 3%. The unknowns are full of fairly simple minerals with decent standards so should match (for this I was using 80-60-40).

**Comment by GGloy** [comment]
Can be closed
