### ISSUE TITLE
Batch Export of Particle Grid

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#280]
Muhammet from RSC has requested the ability to batch export the particle grid images as an option. Will need to think how this will work as we would need to also apply the same "sort" between database before export. but would be a good export feature to have since most Process Met reports the sorted particle images are key.

**Comment by jonathan-knapp** [comment]
@ChiLyMan, will it make more sense to build a python script to do this?

**Comment by ChiLyMan** [comment]
He also wants the ability to export a subset of particles in the grid (e.g. particle with target mineral liberation > xx%) and not just exporting all the particles in a grid. I'm sure we can do this in python, but we are slowly seeing mission creep where Python functions and modules replace AMICS Process. Need to think is this how we want the new Process to operate.

**Comment by jonathan-knapp** [comment]
It is more that we want to not add more features to Process. Let's think about framework and function development, rather than a "program to do" - I do not want to add any more export functions to this release of Process. It than becomes a "how much is this needed" and "what do we need to do to enable lots of *data transformation* options in Python (not really export).

As a general principal I want to move custom features like this into the scripting framework rather than putting it into Process.



-Bruker Confidential-

**Comment by jonathan-knapp** [comment]
This is going to be part of SPARK, not AMICS Process. I am going to close this issue along with all issues that will be done in SPARK. Thank you.
