### ISSUE TITLE
Mineral groupings get corrupted

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#313]
v3.3.01315
Another apparently random one (sorry):
Occasionally reprocessing against an ore type will result in a corrupted mineral grouping (sometimes this will just be in the current results but it can also corrupt the groupings in the ore type too).
Current result groupings after reclassification (many groupings are gone and those that are present are junk):
![image](https://user-images.githubusercontent.com/84986921/198411160-19156e7d-a183-4c97-908d-0a471a5007bd.png)
Mineral groupings as they are in the ore type used:
![image](https://user-images.githubusercontent.com/84986921/198411193-37be09aa-6046-41b1-adbc-77895d46291a.png)

Workaround in this case is to reclassify using the ore type but if the ore type groupings are corrupt, you have to find a measurement with OK groupings and reapply back to the ore type.

**Comment by scarlett-01110011** [comment]
Same - I would like to add a mission critical label

**Comment by jonathan-knapp** [comment]
@MarkGuo7 note that this has been pinned a high priority in the Bug Backlog.

**Comment by MarkGuo7** [comment]
@Matt-Power & @scarlett-01110011 

Hi Matt & Scarlett

Could you try the latest build I uploaded yesterday, 1399?
I will keep an eye on this one. If you notice how to repeat it, that would be very helpful.

Mark

**Comment by jonathan-knapp** [comment]
Is this still an issue? Seems like it was addressed.

**Comment by Matt-Power** [comment]
I believe so. Not sure how to trigger it but it happens regularly. I'll check again next time I'm using 3.3.

**Comment by scarlett-01110011** [comment]
I think this is fixed now, thanks.

**Comment by jkabel** [comment]
I believe this just happened to me in 1399

**Comment by Matt-Power** [comment]
So far I haven't seen it in 3.3.0.1508 so I think that this is fixed in more recent versions.

**Comment by jkabel** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Oh that should probably be thrown up on the releases page then.                                                                                                                                                                                                                                                                                                                        From: ***@***.***: February 9, 2023 11:12 a.m.To: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [Bruker-Amics/bugs_features] Mineral groupings get corrupted (Issue #313)  
So far I haven't seen it in 3.3.0.1508 so I think that this is fixed in more recent versions.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Matt-Power** [comment]
Yeah, the release thing isn't updated very often so you have to reach out to the team. For what it's worth, 1508 seems fairly stable and a lot of those niggles with mineral groupings / ore types getting corrupted are now fixed.

**Comment by jonathan-knapp** [comment]
We are having some stability issues in the most recent build. We are mucking around a lot at the moment. I hope to upload a new version in a week. I spent all day yesterday with Mark and Gerda in person on the SEM.



-Bruker Confidential-
