### ISSUE TITLE
V 3.3.0.1315 - Corrupted image capture on long runs 

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#318]
Corrupted images captured by system on long runs.  Does not appear to be SEM hardware related, as turning on beam again and collecting an image works as expected.

![RC17-CM3-TI-HL-160-Particle_BSE_Image](https://user-images.githubusercontent.com/12158231/199119575-769ceb5d-276d-47eb-b17e-84a959d48184.png)

[Investigator32_2022_10_27_15_08_44.log](https://github.com/Bruker-Amics/bugs_features/files/9905401/Investigator32_2022_10_27_15_08_44.log)

[Investigator32_2022_10_27_15_08_44_Debug-Truncated.log](https://github.com/Bruker-Amics/bugs_features/files/9905415/Investigator32_2022_10_27_15_08_44_Debug-Truncated.log)

**Comment by MarkGuo7** [comment]
@jkabel Thanks Jacob for the log files

From the log file, I can see there is something wrong during measuring:
![image](https://user-images.githubusercontent.com/84481724/199384610-84f6f1ab-3445-42d6-9750-2e9f17bfd01c.png)

AMICS collected the xray failed, so it try to reset communication and redo the same field.
After that, all the images captured are blank.

![image](https://user-images.githubusercontent.com/84481724/199384794-158aab49-08be-41e5-af29-bdba85fd630e.png)

There are two issues, one the xray collection failed, and the reset communication command failed.
I can remove the reset communication command, which I already did in 3.3, because this command do more damage than help.
But don't know how to fix the xray collection failed issue.

Maybe the new scanbox with Esprit 2.5 is better in this case. That's my understanding.

**Comment by jonathan-knapp** [comment]
@ChiLyMan and @MarkGuo7 is this related to an issue where the system is overcorrecting for BSE stability? This is a high-priority issue.

**Comment by ChiLyMan** [comment]
Let me sit with @jkabel today since I am here anyway. We can always try Espirt 2.5 on the system, since it has better handling of comms failure, though that will depend on the SCU installed. We can also test out 3.3 so we can turn of the binary image check.

**Comment by MarkGuo7** [comment]
This one is communication issue, not a binary image issue.

**Comment by ChiLyMan** [comment]
@jkabel is now on Espirt 2.5 and AMICS 3.3 is loaded onto the system He will test to see if this will help resolve the image corruption issues. We've also turned off the binary image option in AMICS 3.3. We can leave this open for a little while and check back with him to see if this issue has been resolved.

**Comment by jonathan-knapp** [comment]
@ChiLyMan did the upgrade fix this?

**Comment by ChiLyMan** [comment]
Not heard any recurrence but just continue to monitor…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GGloy** [comment]
@ChiLyMan do you think this can be closed?

**Comment by ChiLyMan** [comment]
Let close it for now since I've not seen a repeat of this.
