### ISSUE TITLE
Process crash when stitching circular areas (vs1501)

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#328]
In the latest build, if I try to stitch circular measured samples Process crashes!

**Comment by ChiLyMan** [comment]
Just testing this out, and you also can not seem to "Clear All Adjustments". Usually, when you first open the Field Adjustment button the image will already be overlapped, and "Clear All Adjustments" will remove the overlap. This does not seem to be working. 

Could there be an issue with writing or reading from stitching table in the MRE file?

**Comment by ChiLyMan** [comment]
Just tested this and this is correct and repeatable. Additionally. the "Clear All Adjustment" function does not seem to be working. Normally, when sample are initially open, fields are already overlapped. And selecting the "Clear All Adjustment" will clear this initial overlap. current build does not seem to remove this initial overlap

The log does not seem to say much, but the po-up screen seems to crash during the process of "clearing stitching info". 

Could these two behaviors be link? Maybe the fact the Clar all adjustment does not remove the initial overlap then causes the auto stich to fail since it no longer starts at a "zero" point?
