### ISSUE TITLE
BUG - MINOR (but annoying) - AMICS Investigator:  beam idling not working on SU3900

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#376]
v 3.3.0.1701
The beam idling option does not appear to work on the SU3900 during stage moves - there are still burn marks marking the beam position. Tracks are really obvious in the CL image below.

![Beam burn in CL](https://github.com/Bruker-Amics/bugs_features/assets/84986921/c152a56b-333c-47f4-94a0-b7ac5b3392b3)

**Comment by MarkGuo7** [comment]
Hi Matt
Which marks? 
This one: 
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/a7dda3e3-1805-4dcc-92e4-c5b747f98f5a)

Or this one?
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/9ab188fb-aedc-4283-a1e3-a390a707543f)

**Comment by MarkGuo7** [comment]
The first one looks weird, because it is not straight.

The second one is on the left side of frame, right?

**Comment by Matt-Power** [comment]
It's the stage driving to the first frame of a measurement (the stage approaches from the lower right, then slows and approaches from the right only for the backlash correction). It appears that after the measurement is complete, the beam goes back to the centre but not sure why it only shows on the next frame (maybe due to the stage speed slowing as it goes towards the start position of the new frame?)

**Comment by Matt-Power** [comment]
Sorry, just to add, it's the first image that shows the beam idling isn't working. The second one is just where the frames are overlapping so it's two lots of beam damage - only way to fix that is to set the field overlap to exactly 0 which is not practical.

**Comment by MarkGuo7** [comment]
Hi Matt

Let's give it another try.
Since different machine accept different API, so could you try this option.
If the fast scan speed is less than 0, then it will try to freeze/blank the beam. Otherwise will do fast scan.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/9c6f5dc7-24b8-426b-aeec-55d7f3209717)

**Comment by ChiLyMan** [comment]
@Matt-Power Did you get a chance to give this a try to see if it works on the 3900 or 5000 system? Otherwise, we might have to park this one as there is no consistent "beam blank" available over each Hitachi platform.

**Comment by Matt-Power** [comment]
@ChiLyMan @MarkGuo7 It is set on 0 for both the 3900 and 5000 but in both systems, it is still burning a line across the sample. It only seems to happen during the stage move.

I realise that beam blanking is not available for either instrument but this is causing us a lot of problems when post-processing the data so we need to have some sort method to prevent the beam being stationary during stage movements.

**Comment by MarkGuo7** [comment]
Hi Matt

Sorry about that. Seems there is no blank the beam function, so the options is to do fast scan or freeze the beam. Freeze the beam will cost time, so we try to put the scan back to normal before moving stage. 
If the problem still there, there are two things we need to confirm:
1) I will try to put extra logs to see if the switching beam commands work as expected.
2) We actually need to ask Hitachi about this issue. We need to understand what Hitachi doing the beam while moving stage.
Will the beam stay the same position (like now), or there is an option to blank it while moving stage.

From AMICS point, we only can guess and try, because we couldn't touch Hitachi or Esprit code.

**Comment by Matt-Power** [comment]
@MarkGuo7 thanks. Are the options for the idle scan speed just 0 and -1? (i.e. what happens if I set to 1 or 2?)

**Comment by MarkGuo7** [comment]
Hi Matt

It will switch to fast scan speed (1,2) while moving stage. 
We try to keep the beam scanning to avoid this kind of burning.

**Comment by Matt-Power** [comment]
So are both 0 and -1 off? (Your note a few posts above implies that less than 0 is off (and therefore 0 is scan) or did I read it the wrong way? Just want to make sure!
