### ISSUE TITLE
BUG - LOW - AMICS PROCESS - Percentags in "Current Result Standards" list includes deleted segments 3.3.0.1701

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#386]
The modal percentages that appear beside minerals in the current result standard appear to include results from deleted segments but totals appear correct in Calculation Tables tab:

![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/d6dbefd7-7d60-4fde-b24f-2fc5fc1850fd)

I used silver paint on some samples I thought were for LA-ICP-MS, deleted the paint, but the silver still shows up as ~3% in the current result standard list.

I'd call this low priority.

**Comment by jonathan-knapp** [comment]
@ChiLyMan can you run down and see if this is still happening after the UI update?

**Comment by ChiLyMan** [comment]
@knapp-amics Just checked on the newest build and this is still the case. The modal percentages in the group list do not reflect deleted particle/fields

**Comment by jonathan-knapp** [comment]
Thank you @ChiLyMan we will add it to this list for this bashing but also just note that in the release known issues. @jkabel thanks for the report, @MarkGuo7

**Comment by GGloy** [comment]
@ChiLyMan  I checked in vs1846 - if I delete something the calculation tab will reflect the change immediately, but the group list will only update after a re-classification

**Comment by AlexeiDolgolyov** [comment]
@ChiLyMan, that seems to be an old bug that was duplicated with multiple tasks. The real problem is that Result Material Table and Calculation Table are using different calculations, I'm not sure why... 
We can try to make Result Material Table use the same calculation as Calculation Table uses, but I don't know how much time it might consume...

**Comment by jonathan-knapp** [comment]
It appears this was done because it takes too long or something? I am going to close this issue, as it may be fixed in the future with a reconsideration of the entire system. For now, this bug is old and will be a big task to fix. We just need to make sure people know the table on the key is a estimate.
