### ISSUE TITLE
Mineral Groupings Not Working After Reclassification

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#414]
v3.3.1934
Mineral groupings are not being applied after reclassification. The group name is available in the drop-down box but when selected, the minerals all appear to be ungrouped.

**Comment by ChiLyMan** [comment]
@Matt-Power Are you reclassifying from the common library or just refreshing the sample?
If reclassifying from the common library=>Could you check to see if the grouping is correct in the common library standard?
Could you try fix the grouping in the common library standard, before reclassifying using the common mineral library.

The bug seems to occur when transferring the grouping from the Current Result to the Common Library. Once the grouping is "fixed" or modified in the common library it seems to work fine after that...don't know why.

**Comment by Matt-Power** [comment]
@ChiLyMan I was reclassifying from the common library but the groupings appear fine in there.

**Comment by MarkGuo7** [comment]
Hi Matt, I will move this to the QA list. Let me know if you still notice it.

**Comment by ChiLyMan** [comment]
Mark did you build a new version in Deep-CI? I need to download for Matt he does not have access to deep-CI.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarkGuo7** [comment]
Hi Chi

Normally, I will upload the build to the core 3.3 area for Gerda testing.
https://github.com/Bruker-Amics/core/releases/tag/V3.3

The latest one should be 1961.
Let me know if you couldn't access it.

**Comment by ChiLyMan** [comment]
Thanks Mark,

I’ll check in the morning and send to Matt.

Chi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChiLyMan** [comment]
Just tested this on build 1961 and the strange grouping behavior seems to be resolved.
@Matt-Power could you check as well so we can close this if fixed.

**Comment by Matt-Power** [comment]
Think this one is now fixed. Thank you.
