### ISSUE TITLE
Need to switch Esprit to offline to speed up measuring

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#444]
Here is the testings from Gerda:

Hi Mark
 
Here are the results of the speed testing running different modes offline and online - saving ~1minute on 9 fields. (sorry the order for the types is not the same)
 
Where the red arrow is – this was my initial Bright Phase Search, then I clicked in the type and changed it by accident ☹ the measurement did 9 fields in 4min10.
 
 
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd4be7244aa3034837a2ea069678c4f5bd5eb46c/image.png)

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I think this is done, no?

**Comment by ChiLyMan** [comment]
This impacts the SU5000 more than other Hitachi machine. It is related to how the SEM software handles multiple command inputs.
I've tested on newer SU3900, SU7000 and FlexSEM, and the time different between online and offline mode is marginal compared to the SU5000.
Closing because this really just needs input from Hitachi factory, nothing AMICS or Bruker can do about it.
