### ISSUE TITLE
Run Summary Only Saved on Successful Completion

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#45]
The run summary in the batch export is only written at the end of the batch - it should be written / updated after each sample in case of crashes or other termination of the batch. If it is written as it goes, it is also possible to use the data contained while the batch is still running (for large sample batches, it can take several hours to complete).

**Comment by ChiLyMan** [comment]
This has been corrected. The log is progressively updated, and the final summary file is written if all fully successful or partially failed. All samples selected in Batch will have status "OK" "Failed" or "Pending", respectively completed OK, something went wrong and didn't get to because of earlier failure..
