### ISSUE TITLE
Converting Map to Particle and Reclassifying Junks the Measurement

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#468]
v3.3.0.1990
If you convert a map to a particle measurement and then reclassify, the result is junk and there is no apparent way to undo or rescue.

**Comment by ChiLyMan** [comment]
@Matt-Power Can you give me the step you are doing for this to mappen? I just tested this on 1996 and was able to convert Mapping to Particle, and then reclassify without issue.

**Comment by MarkGuo7** [comment]
@ChiLyMan Thanks Chi

I think I got a dataset from one Chinese customer that can repeat this issue.
Currently I am working on something else. Will get it sort out first after my current is done.

**Comment by MarkGuo7** [comment]
Will let you know if need any further helps :)

**Comment by Matt-Power** [comment]
I was using 1990 as it's the latest build that I have been given. The steps were - convert map to particle, reclassify from ore type. The result is a random bunch of dots (mostly white space) and then more often than not, everything crashes.

**Comment by ChiLyMan** [comment]
I just tested this on 1996, and it looks like it is linked to the dataset, as @MarkGuo7  mentioned. On data set collected on older version of AMICS, this does not seem to be an issue. But on a recent one I also got from Chinese client this happen each time. It is as if the link between the xray point and the xray data are disconnected, because you might notice you can not pull up the xray spectra when you hover over the "+" marks anymore.
@Matt-Power Have you also notice white lines between each pixel of your matrix maps?

**Comment by ChiLyMan** [comment]
@MarkGuo7 Might be a hint that this is linked to Dot size. After trashing my data I was fiddling with Spectrum tree, because you can still pull the spectra data there, and I created a branch and assigned spectra from the branch to something. And you can see more dots, as if it only know to show the mineral image with a dot size of 1, even though it has been converted to Particle.
And those white lines I mentioned was linked to the dot size, so could be linked.

**Comment by Matt-Power** [comment]
@ChiLyMan yes, the measurement is actually almost all white lines afterwards (the mineral pixels that remain also look odd - they are tall and thin).

**Comment by ChiLyMan** [comment]
Closed for now as I've not seen this on recent versions
