### ISSUE TITLE
Particulization and Background Improvements 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#6]

**Comment by AHM-amics** [comment]
@markguo7 
All comments below relate to AMICS v3.1.1.2150

I have been playing with the Particulation Feature in AMICS with MicroXRF. This is a great feature and very powerful and will be of great benefit to numerous of our clients.

Sample Description: These are different minerals (mostly salts and sulphates) mounted in 30mm resin blocks. These samples also have different size fractions. I have been running some tests on these as they are simple systems and ideal for test work. I have done measurements of all three size fractions at different pixel spacing, i.e. 100um, 50um, 20um, and 10um and at different times etc. All measurements were over the same area for each sample with movement or changing the M4 conditions except for the variable that was changed. For this discussion below I am focusing on two measurements only: (i) a measurement at 100um (labelled Salt-100um) and a measurement at 50um (labelled Salt-50um), which are uploaded into the link.

Each measurement is of a 10x10mm area. There is a Mineral Standards Group 1 which should be used for viewing. I have done some simple processing, including generating mixed spectra which are appropriately grouped in the Mineral Standards Group 1.

LINK:  https://1drv.ms/u/s!AiQ95bfsvcO8hcpjkSlcuq8mQJ2a-Q?e=e0FYvW

Here are some of my comments and observations. I have specifically tailored these comments to two data sets uploaded at the following link:

1.	Sample 100um

The particulation function works as planned.

Process: Click “Particulation” button. In the “pop-up” window select “Unknown” + “Low Counts” + Un_x_Rayed” + “Shadows” + “Pores”. 
Outcome: All are removed and then the samples can be investigated using the particle selection (where Frame used to be) and the options such as “liberation” and “lockability” are available.

2.	Sample 050um

The particulation function does NOT work. 

Process: Same as above. Click “Particulation” button. In the “pop-up” window select “Unknown” + “Low Counts” + Un_x_Rayed” + “Shadows” + “Pores”. 
Outcome: Nothing happens. 

Process: Select other minerals, e.g. “Halite”. The Halite pixels are removed.

3.	Sample 050um

Alternative solution to get the particulation to work.

Process: Using Mineral Standard Group 1 and Particle Grid, select the cell labelled “Other” (which contains “Unknown” + “Low Counts” + Un_x_Rayed” + “Shadows” + “Pores” as a group), right click, and click on “Select all particles of Cell”. Then deleted.
Outcome: Now the “Other” are deleted. However, Because it is not Particulated the options such as Liberation and Lockability are not available.
Continued Process: Now go to “Particulation” and select “Unknown” + “Low Counts” + Un_x_Rayed” + “Shadows” + “Pores”. Now the sample “Particulates” correctly. And the Liberation and Lockability options are available.

4.	Other observations:

Undoing or Reversing a Particulation: How is this done? 

Comment: After a “particulation” is complete the “delete” button (and thus the undo delete) is greyed out. As is the Undo button. Thus the process is “non-reversable”? Is this the idea?

Observation: When clicking the “Particulation” button a second time, no “popup” window for mineral selection occurs, however the delete button becomes activated and deleted items can be restored.

Bcf Import: I have also included the bcf files so you can test the importing. Currently due to the new method of saving each detector in the bcf file only 50% of the data is imported into AMICS.

**Comment by MarkGuo7** [comment]
@AHM-amics Thanks Andrew, I think Van is the person you should mention :)

**Comment by AHM-amics** [comment]
@phan this comment thread is for you

**Comment by AHM-amics** [comment]
@van-amics Hi Van. This comment thread is for you. Let me know if you have questions.
