### ISSUE TITLE
Process an open database in batch process

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#62]
![Batching_Error](https://user-images.githubusercontent.com/84643841/122472754-9a866b80-cf86-11eb-8660-d31f9f544c7c.JPG)

Still getting the error trying to run a batch when the database is opened by AMICS.

**Comment by knapp-amics** [comment]
@van-amics this is something that is a big hindrance in the workflow. Is it possible to overcome this?

**Comment by GGloy** [comment]
What was the solution here?

**Comment by van-amics** [comment]
When this dialog box is shown, you can switch to the other open Process and close the measurement there, then get back to this and click "Try Again" to continue.

**Comment by GGloy** [comment]
@ChiLyMan does the solution resolve your issue? Thanks!

**Comment by jonathan-knapp** [comment]
Van,
Is it possible to add a close command that would close the file and then re-open it when the batch is finished with that particular file? You can Structure it as a function that executes the closed command and closes the SQL database performs the batch on that particular file and then reopens?

Thoughts? It may be nice to even just have a close command in the file so that you can close the file in process without having to shut the program down.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by van-amics** [comment]
Hi Jonathan,

Currently AMICS Process has already a "Close" command to close the opening file (and left the Process main screen blank, as if it was just being launched).

To automatically close an open file from another running Process may have complications. For example, the other running Process may be in the middle of a lengthy operation (it may run another batch, for example), then the initial Process must decide to kill the other (may put its databases in an invalid state) or wait (gaining little, if wait). The other Process may have dirty data it needs to save etc.

That's why, the cheapest solution is popping up a message box and let the user handle it. It's certain not elegant, but we can always improve it later on.




-Bruker Confidential-

**Comment by ChiLyMan** [comment]
Hi Guys,

 

I would think a short-term solution is as you say Van, allow the user to decide if shutting the other process down is ok or not.

 

Once this is in place, we can test it and find out if the worst case as you mentioned is something that will happen during normal operations, if not we can always just change the message box to become the automated shutdown as Jonathan suggests.

 

Thoughts?

**Comment by jonathan-knapp** [comment]
Ok Van. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
