### ISSUE TITLE
Failing to open database

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#83]
I'm having trouble opening a data base I recently got from Nigel who is rerunning the samples for me. 

I know Nigel recently updated to latest version of the software so that might be the issue. I'm still running  v3.1.1.2305.

I tried to upload the data file here but github would not accept the zip file for some reason.

In case you need an example of the database I've included a link below:-
https://mega.nz/file/exgEXC5S#PVOrOmrH5g5xyB657qwdv5IZjzq4lx9b04OMO-N2Ors

If possible if someone could just send me the latest version I can install it and see if that fixes the problem.

Cheers

**Comment by jonathan-knapp** [comment]
Select "Releases" to the right
***@***.***



- confidential -
From: ChiLyMan ***@***.***>
Sent: Wednesday, July 28, 2021 6:40 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Failing to open database (#83)

**EXTERNAL EMAIL**

I'm having trouble opening a data base I recently got from Nigel who is rerunning the samples for me.

I know Nigel recently updated to latest version of the software so that might be the issue. I'm still running v3.1.1.2305.

I tried to upload the data file here but github would not accept the zip file for some reason.

In case you need an example of the database I've included a link below:-
https://mega.nz/file/exgEXC5S#PVOrOmrH5g5xyB657qwdv5IZjzq4lx9b04OMO-N2Ors

If possible if someone could just send me the latest version I can install it and see if that fixes the problem.

Cheers

-

**Comment by ChiLyMan** [comment]
Sorry If I am blind, I can not find "Releases: anywhere. Is it in a submenu?

![image](https://user-images.githubusercontent.com/84643841/127414892-bcc6cafd-70f6-4c51-b529-6082dccce9e9.png)
![image](https://user-images.githubusercontent.com/84643841/127414913-ef09c2f7-1ea4-47ca-a11b-962f1ed19fc6.png)

**Comment by ChiLyMan** [comment]
never mind, Nigel version to me, testing it now.

**Comment by ChiLyMan** [comment]
Fixed with new version!
