### ISSUE TITLE
Virtual Standards

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#91]
Can we have the ability to create virtual standards please? This would be a massive help in processing using the spectrum tree. Pulling out solid solution detail or separating phases is incredibly tricky and time consuming given that new standards often have to be created and these change the data, therefore the spectrum tree also changes etc etc.

These would be "standards" to which you can assign spectra in spectrum tree but which are not used for the measurement or the main spectral matching algorithm. This would make processing so much easier, especially for splitting things based on degree of solid solution and other subtle effects which are only successful in the spectrum tree.

On possible option(?) would be to add another "State" such as "Virtual" in addition to the Normal, High, Low, Invalid (I did try creating an invalid entry to see if I could work-around but it won't let me classify the data with invalid entries).

Another advantage would be that processing could become much, much quicker as far fewer proper standards would be needed.

As an example, currently, if I want to split muscovite into several groupings based on the Al/Si ratio and call them Mica 1, Mica 2 etc, I have to create standards for each, reprocess the data (which will then change because of the new entries), edit any relevant spectrum tree steps which have been affected (this in itself usually means reprocessing data at least two more times), then create a new spectrum tree step to capture the new groups. 

Virtual standards would simplify this enormously and allow tweaking to pull out detail without fundamentally changing the underlying data. This is a really important feature for me so if it is possible to integrate with the hierarchical matching for the current release, it would very much appreciated.

**Comment by jonathan-knapp** [comment]
Matt,
The concept of separating the "Material Definitions" from the "Spectral Reference" is in the near-term road map. We will address this directly after we address project management. What you describe will just be the normal way standards operate with either a spectrum tree step or a spectral reference pointing to a definition.

-Jonathan



- confidential -
From: Matt-Power ***@***.***>
Sent: Friday, August 6, 2021 2:17 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Virtual Standards (#91)

**EXTERNAL EMAIL**

Can we have the ability to create virtual standards please? This would be a massive help in processing using the spectrum tree. Pulling out solid solution detail or separating phases is incredibly tricky and time consuming given that new standards often have to be created and these change the data, therefore the spectrum tree also changes etc etc.

These would be "standards" to which you can assign spectra in spectrum tree but which are not used for the measurement or the main spectral matching algorithm. This would make processing so much easier, especially for splitting things based on degree of solid solution and other subtle effects which are only successful in the spectrum tree.

On possible option(?) would be to add another "State" such as "Virtual" in addition to the Normal, High, Low, Invalid (I did try creating an invalid entry to see if I could work-around but it won't let me classify the data with invalid entries).

Another advantage would be that processing could become much, much quicker as far fewer proper standards would be needed.

As an example, currently, if I want to split muscovite into several groupings based on the Al/Si ratio and call them Mica 1, Mica 2 etc, I have to create standards for each, reprocess the data (which will then change because of the new entries), edit any relevant spectrum tree steps which have been affected (this in itself usually means reprocessing data at least two more times), then create a new spectrum tree step to capture the new groups.

Virtual standards would simplify this enormously and allow tweaking to pull out detail without fundamentally changing the underlying data. This is a really important feature for me so if it is possible to integrate with the hierarchical matching for the current release, it would very much appreciated.

-

**Comment by Matt-Power** [comment]
OK, thanks. As long as we can create the definitions ad-hoc from the spectrum tree (or wherever) and they are essentially empty containers not used during the spectral matching but filled afterwards, that should work and allow the list used for direct spectral matching to be slimmed down a lot.
